name: Build and test package

on:
  push:
    # https://stackoverflow.com/questions/68573888/how-can-i-not-execute-a-github-action-when-i-push-a-new-tag
    branches:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
      - 'src/lib/**'
      - '*.js'
      - '*config*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          npm ci
      - name: Check code style with linter
        run: |
          npm run lint
      - name: Run tests
        run: |
          npm run test
      - name: Build package
        run: |
          npm run build
