name: Build and test package

on:
  push:
    # https://stackoverflow.com/questions/68573888/how-can-i-not-execute-a-github-action-when-i-push-a-new-tag
    branches:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
      - 'src/lib/**'
      - '*.js'
      - '*config*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          npm ci
      - name: Run linter
        id: lint
        run: |
          npm run lint
      # https://stackoverflow.com/questions/57850553/github-actions-check-steps-status
      - name: Fix lint errors
        if: job.steps.lint.status == failure()
        permissions:
          contents: write
        run: |
          npm run format
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "chore: Automatic code style fix"
          git push
      - name: Build package
        run: |
          npm run build
