name: Build and test package

on:
  push:
    # https://stackoverflow.com/questions/68573888/how-can-i-not-execute-a-github-action-when-i-push-a-new-tag
    branches:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
      - 'src/lib/**'
      - '*.js'
      - '*config*'
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-branches
    branches:
      - chore/bump-package-version-to-**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: |
          npm ci
      - name: Check code style with linter
        run: |
          npm run lint
      - name: Run tests with coverage
        run: |
          npm run coverage
      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build package
        run: |
          npm run build
