name: Publish package to npmjs
on:
  # https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Extract package version
        id: package-version
        # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
        run: |
          echo "tag=$(echo ${{ github.ref_name }} | tr -d v)" >> $GITHUB_OUTPUT
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Bump version
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
        run: |
          sed -Ei 's/"version":[ ]+"[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?"/"version": "'${{ steps.package-version.outputs.tag }}'"/g' package.json
          echo $(cat package.json)
      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Publish version change
        # https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action
        # https://cli.github.com/manual/gh_pr_create
        # https://cli.github.com/manual/gh_pr_merge
        run: |
          git pull
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git checkout -b feature/bump-package-version-to-${{ steps.package-version.outputs.tag }}
          git commit -am "infra: Bumped package version to ${{ github.ref_name }}"
          git push origin feature/bump-package-version-to-${{ steps.package-version.outputs.tag }}
          gh pr create \
            -H feature/bump-package-version-to-${{ steps.package-version.outputs.tag }} \
            -B master \
            -t "infra: Bumped package version to ${{ github.ref_name }}" \
            -b "Automated PR to bump package version"
          gh pr merge --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_PR_CREATION_TOKEN }}