name: Publish package to npmjs
on:
  # https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(.[0-9]+)?'
jobs:
  publish package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Bump version
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: |
          PACKAGE_VERSION=$(echo ${{ github.ref_name }} | tr -d v)
          sed -E 's/"version":[ ]+"[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/"version":"${{}}"/gg' package.json
      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
