name: Publish package to npmjs
on:
  # https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: npm ci
      - name: Bump version
        # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
        run: |
          PACKAGE_VERSION=$(echo ${{ github.ref_name }} | tr -d v)
          echo "$PACKAGE_VERSION"
          sed -Ei 's/"version":[ ]+"[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?"/"version":"'${PACKAGE_VERSION}'"/g' package.json
          echo $(cat package.json)
      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Commit version change
        run: |
          git checkout master
          git pull
          git config --global user.name 'totocorpbot'
          git config --global user.email 'totocorpbot@users.noreply.github.com'
          git commit -am "infra: Bumped package version to ${{ github.ref_name }}"
          git push
